[package]
name = "ferrite"
version = "0.1.0"
std = "c23"
compiler = "clang"

[[target]]
name = "ferrite"
type = "executable"
src = ["src/**/*.c", "emu/**/*.c"]
include = ["include"]
out = "build"
links = []

[[target]]
name = "fasm"
type = "executable"
src = ["asm/**/*.c", "emu/**/*.c"]
include = ["include", "asm/include"]
out = "build"
links = []

[profile.debug]
flags = ["-g", "-fsanitize=address,undefined", "-O0", "-D_POSIX_C_SOURCE=200809L", "-Wall", "-fcolor-diagnostics"]

[profile.release]
flags = ["-O3", "-DNDEBUG", "-march=native", "-Wall", "-D_POSIX_C_SOURCE=200809L", "-fcolor-diagnostics"]

[install]
prefix = "/usr/local"
